analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#040718'
    - '#00B8FB'
    - '#1C3CB7'
    - '#6572E5'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.285472
  saturation: 0.722973
cta: {}
layout_spectrum: 1
name: e-blog
opengraph: {}
purpose:
  - name: shares
typography_spectrum: 0.27807
