analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#040718'
    - '#00b8fb'
    - '#1c3cb7'
    - '#6572e5'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0
  saturation: 0.5
cta: {}
layout_spectrum: 0.7696
name: e-blog
opengraph: {}
purpose:
  - name: shares
typography_spectrum: 0.194256
