name: null
favicon: null
layout_spectrum: 0.7696
typography_spectrum: 0.27807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040718'
    - '#00b8fb'
    - '#1c3cb7'
    - '#6572e5'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: shares
    item: null
    url: null
